---
title: "Fund Comparisons"
author: "Robert Schnitman"
date: December 22, 2019
output:
  pdf_document: default
  
---

```{r setup, include=FALSE}
### 1. Import Stocks.
libs <- c('tidyverse', 'knitr', 'kableExtra', 'quantmod', 'stargazer')
lapply(libs, library, character.only = TRUE)

funds <- c('SWPPX', 'ROGSX', 'SWMCX', 'SCHH', 'SCHM', 'SCHK')

for (i in funds) {
  
  getSymbols(i, src = 'yahoo')
  
}

funds_data <- list(SWPPX, ROGSX, SWMCX, SCHH, SCHM, SCHK) %>%
  set_names(funds) %>%
  map(as.data.frame) %>%
  map(~ mutate(.x, Date = rownames(.x)))

stocks <- funds_data %>%
  plyr::join_all(by = 'Date')

### 2. Create daily-percent-change function.
pctchg <- function(s, n = 1) {(s/lag(s, n)) - 1}

### 3. Calculate percent changes
stocks2  <- stocks[, grep('Adjusted', names(stocks), value = TRUE)]

pctchg_df <- map_dfc(stocks2, pctchg) %>%
  mutate(Date = stocks$Date) %>%
  na.omit()

msd <- pctchg_df %>%
  select(contains('Adjusted')) %>%
  map(~ c(Mean = mean(.x, na.rm = TRUE), SD = sd(.x, na.rm = TRUE))) %>%
  do.call(rbind, .)

msd2 <- msd*100

rownames(msd2) <- gsub('\\.Adjusted', '', rownames(msd))

```

# Table 1. Mean Daily Returns Since `r min(stocks$Date)`
```{r s1, echo = FALSE, message = FALSE, warning = FALSE}
mycolors <- c('forestgreen', 'salmon', 'gold', 'cyan3', 'tomato4', 'gray4')

col_alpha  <- apply(sapply(mycolors, col2rgb)/255, 
                    2, 
                    function(x) {
                      
                      rgb(x[1], x[2], x[3], alpha = 0.40)
}) 
# REFERENCE: https://magesblog.com/post/2013-04-30-how-to-change-alpha-value-of-colours-in/


format_pct <- function(x, d) {apply(x, 2, function(x) ifelse(!is.na(x), paste0(round(x, d), '%'), ''))}

msd3 <- format_pct(msd2, 2)[order(-msd2[, 'Mean']), ]

kable(msd3, booktabs = TRUE, linesep = '', align = 'r') %>%
  kable_styling(full_width = TRUE)

ggplot(as.data.frame(msd2), aes(x = reorder(rownames(msd2), -Mean), y = Mean, fill = rownames(msd2))) + 
  geom_col(alpha = 0.5) + 
  scale_fill_manual(values = mycolors, guide = FALSE) +
  labs(x = '',
       y = 'Mean Daily Returns (%)',
       title = paste0('Fig. 1 Average Daily % Returns Since ', min(stocks$Date))) + 
  theme_light() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
```

# Table 2. Annual Returns
```{r s2, echo = FALSE, message = FALSE, warning = FALSE}
funds_data2 <- list(SWPPX, ROGSX, SWMCX, SCHH, SCHM, SCHK)

ret_yr <- map(funds_data2, yearlyReturn) %>%
  set_names(funds) %>%
  map2(funds, ~ {
    
    colnames(.x)[1] <- .y
    
    .x
    
  }) %>%
  map(~ format_pct(.x*100, 2))

ret_yr2 <- map(ret_yr, as.data.frame, stringsAsFactors = FALSE) %>%
  map(~ mutate(.x, Date = rownames(.x))) %>%
  plyr::join_all(., by = 'Date') %>%
  select(Date, everything()) %>%
  map_df(~ replace(.x, is.na(.x), '-')) %>%
  as.data.frame()

rownames(ret_yr2) <- ret_yr2$Date

ret_yr2$Date <- NULL

ret_yr2 <- ret_yr2[, sort(colnames(ret_yr2))]

kable(ret_yr2, booktabs = TRUE, align = 'r', linesep = '') %>%
  kable_styling(full_width = TRUE)
```

```{r s2b, echo = FALSE, message = FALSE, warning = FALSE}
ret_yr3 <- ret_yr2 %>%
  map_df(~ gsub('%', '', .x)) %>%
  map_df(as.numeric) %>%
  mutate(Date = rownames(ret_yr2))

pivot <- ret_yr3 %>%
  gather(Fund, Annual_return, 1:(NCOL(.)-1))

ggplot(pivot) + 
  aes(y = Annual_return, x = as.Date(Date), fill = Fund) + 
  scale_fill_manual(values = mycolors) +
  geom_col(alpha = 0.5, position = 'dodge') + 
  labs(y = 'Annual Return (%)',
       x = 'Date',
       title = 'Fig. 2 Annual Returns of Funds') +
  theme_light()
```

```{r s2c, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
# Table 3. Pearson Correlations (Pairwise-Complete Observations)
cors <- ret_yr3 %>%
  cor(use = 'pairwise.complete.obs')

kable(cors, booktabs = TRUE, linesep = '') %>%
  kable_styling(full_width = TRUE)

```
*End of Document*