<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width">
<meta property="og:title" content="The Narrator and the Noise" />




<meta name="author" content="Robert Schnitman" />

<meta name="date" content="2020-01-20" />

<meta name="description" content="The Narrator and the Noise">

<script id="pandoc-meta" type="application/json">
{"newpage_html_class":"page-break-after","date":"January 20, 2020","subtitle":"The Use of Statistical Bias in a Minigame to Emphasize a Thematic Outcome in Act 1 of <em>Doki Doki Literature Club</em>","output":{"pagedown::html_paged":{"self_contained":null,"toc":"true"}},"author":"Robert Schnitman","knit":"pagedown::chrome_print","title":"The Narrator and the Noise"}
</script>

<title>The Narrator and the Noise</title>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
(function() {
  // Retrieve previous config object if defined
  window.PagedConfig = window.PagedConfig || {};
  let beforePaged = PagedConfig.before;
  window.PagedConfig.before = async () => {
    if (beforePaged) await beforePaged();
    return new Promise((resolve, reject) => {
      var script = document.createElement("script");
      script.type = "text/javascript";
      var src = `https://mathjax.rstudio.com/latest/MathJax.js` + "?config=TeX-MML-AM_CHTML";
      if (location.protocol !== "file:" && /^https?:/.test(src))
        src = src.replace(/^https?:/, '');
      script.src = src;
      window.MathJax = {
        AuthorInit: () => {
          MathJax.Hub.Register.StartupHook("Begin", () => {
            MathJax.Hub.Queue(resolve);
          });
        }
      };
      document.getElementsByTagName("head")[0].appendChild(script);
    });
  };
})();
</script>

<script src="DDLC_web-alt_files/header-attrs-2.1/header-attrs.js"></script>
<link href="DDLC_web-alt_files/paged-0.9.1/css/default-fonts.css" rel="stylesheet" />
<link href="DDLC_web-alt_files/paged-0.9.1/css/default-page.css" rel="stylesheet" />
<link href="DDLC_web-alt_files/paged-0.9.1/css/default.css" rel="stylesheet" />
<script src="DDLC_web-alt_files/paged-0.9.1/js/config.js"></script>
<script src="DDLC_web-alt_files/paged-0.9.1/js/paged.js"></script>
<script src="DDLC_web-alt_files/paged-0.9.1/js/hooks.js"></script>
<script src="DDLC_web-alt_files/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>



</head>

<body>

<div class="running-h1-title"></div>

<div class="running-h2-title"></div>



<div class="front-page">
<div id="header" class="title-page">
<h1 class="title">The Narrator and the Noise</h1>
<h1 class="subtitle"><span>The Use of Statistical Bias in a Minigame to Emphasize a Thematic Outcome in Act 1 of <em>Doki Doki Literature Club</em></span></h1>
<h2 class="author">Robert Schnitman</h2>
<h2 class="date">January 20, 2020</h2>
</div>
</div>

<div class="front-matter-container">
<div id="TOC" class="level1 toc front-matter">
<ul>
<li><a href="#index">Introduction</a></li>
<li><a href="#methodology"><span class="toc-section-number">1</span> Methodology</a>
<ul>
<li><a href="#overview"><span class="toc-section-number">1.1</span> Overview</a></li>
<li><a href="#models"><span class="toc-section-number">1.2</span> Models</a></li>
<li><a href="#hypotheses"><span class="toc-section-number">1.3</span> Hypotheses</a></li>
</ul></li>
<li><a href="#data"><span class="toc-section-number">2</span> Data</a>
<ul>
<li><a href="#overview-1"><span class="toc-section-number">2.1</span> Overview</a></li>
<li><a href="#setup"><span class="toc-section-number">2.2</span> Setup</a>
<ul>
<li><a href="#r-code-setup"><span class="toc-section-number">2.2.1</span> R Code: Setup</a></li>
</ul></li>
<li><a href="#import"><span class="toc-section-number">2.3</span> Import</a>
<ul>
<li><a href="#r-code-import"><span class="toc-section-number">2.3.1</span> R Code: Import</a></li>
</ul></li>
</ul></li>
<li><a href="#results"><span class="toc-section-number">3</span> Results</a>
<ul>
<li><a href="#overview-2"><span class="toc-section-number">3.1</span> Overview</a></li>
<li><a href="#distribution-of-points"><span class="toc-section-number">3.2</span> Distribution of Points</a>
<ul>
<li><a href="#r-code-distribution-of-points"><span class="toc-section-number">3.2.1</span> R Code: Distribution of Points</a></li>
</ul></li>
<li><a href="#central-tendency-of-the-points"><span class="toc-section-number">3.3</span> Central Tendency of the Points</a>
<ul>
<li><a href="#r-code-central-tendency-of-the-points"><span class="toc-section-number">3.3.1</span> R Code: Central Tendency of the Points</a></li>
<li><a href="#r-code-central-tendency-of-the-points-bar-graph"><span class="toc-section-number">3.3.2</span> R Code: Central Tendency of the Points Bar Graph</a></li>
</ul></li>
<li><a href="#anova"><span class="toc-section-number">3.4</span> ANOVA</a>
<ul>
<li><a href="#r-code-anova-models"><span class="toc-section-number">3.4.1</span> R Code: ANOVA Models</a></li>
</ul></li>
<li><a href="#tukey-hsd"><span class="toc-section-number">3.5</span> Tukey HSD</a>
<ul>
<li><a href="#r-code-tukey-hsd-tests"><span class="toc-section-number">3.5.1</span> R Code: Tukey HSD Tests</a></li>
</ul></li>
<li><a href="#anova-residual-diagnostics"><span class="toc-section-number">3.6</span> ANOVA Residual Diagnostics</a>
<ul>
<li><a href="#r-code-residuals-setup"><span class="toc-section-number">3.6.1</span> R Code: Residuals Setup</a></li>
<li><a href="#r-code-residuals-distributions"><span class="toc-section-number">3.6.2</span> R Code: Residuals Distributions</a></li>
</ul></li>
<li><a href="#kruskal-wallis-test"><span class="toc-section-number">3.7</span> Kruskal-Wallis Test</a>
<ul>
<li><a href="#r-code-kruskal-wallis-test"><span class="toc-section-number">3.7.1</span> R Code: Kruskal-Wallis Test</a></li>
</ul></li>
<li><a href="#dunn-test"><span class="toc-section-number">3.8</span> Dunn Test</a>
<ul>
<li><a href="#r-code-dunn-test"><span class="toc-section-number">3.8.1</span> R Code: Dunn Test</a></li>
</ul></li>
</ul></li>
<li><a href="#conclusion"><span class="toc-section-number">4</span> Conclusion</a>
<ul>
<li><a href="#discussion"><span class="toc-section-number">4.1</span> Discussion</a></li>
<li><a href="#limitations"><span class="toc-section-number">4.2</span> Limitations</a></li>
</ul></li>
<li><a href="#references">References</a></li>
<li><a href="#appendix-a---full-dataset">Appendix A - Full Dataset</a>
<ul>
<li><a href="#r-code-full-dataset">R Code: Full Dataset</a></li>
</ul></li>
<li><a href="#appendix-b---scatter-plots">Appendix B - Scatter Plots</a>
<ul>
<li><a href="#r-code-scatter-plots">R Code: Scatter Plots</a></li>
</ul></li>
</ul>
</div>
</div>

<div class="main">
<div id="index" class="section level1 unnumbered" number="">
<h1>Introduction</h1>
<p><em>Doki Doki Literature Club</em> (henceforth known as DDLC), developed by Team Salvato,<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> is a visual novel video game that initially appears as an average Japanese dating simulator, eventually shifting into the horror genre and being supplemented with meta-elements that affect the game’s interface and audio.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> Such conventions have propagated inquiries by scholars, such as David Neri (2017), who comments that the “deliberate breaks in the 4th wall” humanizes the characters.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> While this observation is noteworthy, the simple minigame that DDLC employs is of particular interest.</p>
<p>During Acts 1 and 2 of the game, a minigame called “Poem Game” occurs. For 20 rounds, the player chooses a word from a list of 10.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> Selecting specific words grants between one to three points toward Natsuki, Sayori, and Yuri–if a character finds a word to be most affable, their jumping animation plays to indicate that they have received the most points. As with a typical dating simulator, the character that receives the most points will grant additional scenes with said character. While other scholars comment that this minigame is used as essentially a red herring,<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> what they have not explored is how this poem minigame is used in the context of the plot from a <em>numerical</em> standpoint. Particularly, whether the distribution of points is geared toward a specific character and how that may affect the interpretation of the game’s themes.</p>
<p>As such, the focus of this study is to determine the existence and extent of statistical bias towards any of the DDLC characters with respect to the points distribution of the Poem Minigame. The results of this study show that the bias is towards Sayori (2.180 +/- 0.819 vs. overall mean of 1.962 +/- 0.839), who is the first character in the game to experience a traumatic outcome, suggesting that the statistical component of the Poem Minigame–whether intentional or not–attempts to gear the player towards her to accentuate further the emotional impact of her death in Act 1.</p>
</div>
<div id="methodology" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Methodology</h1>
<div id="overview" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Overview</h2>
<p>Using the R programming language, the methods used were frequency distributions, means and standard deviations (SDs), ANOVA, and the Tukey HSD method. The frequency distributions are used to compare the spread of points across each DDLC character that receives points in the Poem Minigame: Natsuki, Sayori, and Yuri. This method allows the detection of outliers or general patterns of the distribution among these characters. The means and SDs would reveal the central tendencies of the distributions, complimenting the ANOVA and Tukey HSD analysis that test whether there exists statistically significant differences among and between the average number of points of the characters. If a statistically significant difference exists, it would indicate that there is “bias” in the distribution of points, since one would presume a uniform distribution of points in a fair game. However, ANOVA assumes a normal distribution of the residuals: if this condition is not met, then the Kruskal-Wallis<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> and Dunn Tests<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> will be conducted, as they do not assume normally distributed residuals.<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
</div>
<div id="models" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Models</h2>
<p>The models are defined as follows:
<span class="math display">\[Model1:Value = \mu_1 + Character_{1i} + \epsilon_{1ij}\]</span>
<span class="math display">\[Model2:log(Value) = \mu_2 + Character_{2i} + \epsilon_{2ij},\]</span>
where <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> are the common effects; <span class="math inline">\(Character_{1i}\)</span> and <span class="math inline">\(Character_{2i}\)</span> are the treatment variables (which represent the DDLC characters in the Poem Minigame); and epsilons are the error terms for their respective models. These models will be estimated by ANOVA and the Kruskal Wallis Test; however, for the latter, only Model 1 will be estimated, as Model 2 is an attempt to normalize the residuals without resorting to a non-parametric test: if its residuals are not normally distributed, then the Kruskal Wallis test is necessary.</p>
</div>
<div id="hypotheses" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Hypotheses</h2>
<p>The following are the hypotheses:
<span class="math display">\[H_0: \mu_{Natsuki} = \mu_{Sayori} = \mu_{Yuri}\]</span>
<span class="math display">\[H_1: \mu_{Natsuki} \neq \mu_{Sayori} \neq \mu_{Yuri},\]</span>
where each of the <span class="math inline">\(\mu\)</span>’s represents the means for a particular character. If the means are relatively similar, then we cannot make a case that there is bias in the distribution of points in the Poem Minigame. Otherwise, the mean points among the characters are not equal and thus the distribution of points may be biased towards a particular character, where we define a statistically significant difference when p &lt; 0.05. So, in this paper, I expect that the minigame gears the player toward Sayori based on the events leading to the end of Act 1.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
</div>
</div>
<div id="data" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Data</h1>
<div id="overview-1" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Overview</h2>
<p>The data for the points distribution of the Poem Minigame were obtained from the Doki Doki Literature Club wiki,<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a> being stored in a comma-separated-values (CSV) file for importing into R–there are a total of 228 words recorded. What follows is the R code that loads the necessary libraries for analysis, importing and displaying the first few rows of the dataset (see <em>Appendix A</em> for the full display).</p>
<p>Each character can receive 1 to 3 points, depending on the player’s selection of the words. Generally speaking, Natsuki prefers “cute” and shorter words such as “boop,”" whereas Yuri opts for more complex ones such as “vivacious.” If a player picks something of the former, Natsuki receives more points and Yuri receives fewer (see <em>Appendix B</em> for visualizations of the point-distribution relationships between the characters). Sayori, on the other hand, prefers words that can be happy such as “awesome” or bittersweet such as “raincloud.”</p>
<p>The subsections <em>Setup</em> and <em>Import</em> below show the R code that loads the necessary libraries for analysis and import steps, respectively.</p>
</div>
<div id="setup" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Setup</h2>
<p>Before the analysis is conducted in R, a set of libraries are loaded for data management, presentation, and methodological purposes. First, the <code>tidyverse</code> library is loaded for its data management and plotting functions (primarily from <code>dplyr</code> and <code>ggplot2</code>), where <code>magrittr</code> is loaded for its convenient update pipe operator (<code>%&lt;&gt;%</code>) that allows one simultaneously to pass and update their data object. The libraries <code>knitr</code> and <code>kableExtra</code> are loaded so that the presentation of the tables can match closer to that of the APA style. The library <code>broom</code> is used to convert model and statistical test outputs into a data frame that <code>knitr</code> and <code>kableExtra</code> functions can accept. The <code>gridExtra</code> library is used to combine <code>ggplot2</code> functions together. Finally, the <code>FSA</code> library is used to conduct Dunn’s Test as a post-hoc procedure to Kruskal-Wallis.<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a></p>
<p>For reproducibility purposes, a function <code>try_load()</code> is created: it attempts to find out whether a library has already been installed, and if not, attempts to install and load it. The function <code>Map()</code> is then used to iterate through loading the aforementioned libraries. Afterward, the next step is to import the data.</p>
<div id="r-code-setup" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> R Code: Setup</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># Name libraries to use for analysis.</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>libs &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;tidyverse&#39;</span>,  <span class="co"># For data management.</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>          <span class="st">&#39;magrittr&#39;</span>,   <span class="co"># For data management.</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>          <span class="st">&#39;knitr&#39;</span>,      <span class="co"># For presenting tables.</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>          <span class="st">&#39;kableExtra&#39;</span>, <span class="co"># For presenting tables.</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>          <span class="st">&#39;broom&#39;</span>,      <span class="co"># For tidying models/tests.</span></span>
<span id="cb1-7"><a href="#cb1-7"></a>          <span class="st">&#39;gridExtra&#39;</span>,  <span class="co"># For placing plots on a grid.</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>          <span class="st">&#39;FSA&#39;</span>)        <span class="co"># For Dunn&#39;s Test</span></span>
<span id="cb1-9"><a href="#cb1-9"></a></span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="co"># Write function for loading libraries or installing them if not available.</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>try_load &lt;-<span class="st"> </span><span class="cf">function</span>(x) { </span>
<span id="cb1-12"><a href="#cb1-12"></a>  </span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="cf">if</span> (<span class="op">!</span><span class="kw">require</span>(x, <span class="dt">character.only =</span> <span class="ot">TRUE</span>)) {</span>
<span id="cb1-14"><a href="#cb1-14"></a>    </span>
<span id="cb1-15"><a href="#cb1-15"></a>    <span class="kw">install.packages</span>(x)</span>
<span id="cb1-16"><a href="#cb1-16"></a>    <span class="kw">library</span>(x, <span class="dt">character.only =</span> <span class="ot">TRUE</span>)</span>
<span id="cb1-17"><a href="#cb1-17"></a>  </span>
<span id="cb1-18"><a href="#cb1-18"></a>  }</span>
<span id="cb1-19"><a href="#cb1-19"></a>  </span>
<span id="cb1-20"><a href="#cb1-20"></a>}</span>
<span id="cb1-21"><a href="#cb1-21"></a></span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="co"># Load libraries</span></span>
<span id="cb1-23"><a href="#cb1-23"></a><span class="kw">Map</span>(try_load, libs)</span></code></pre></div>
</div>
</div>
<div id="import" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Import</h2>
<p>To import the dataset into R, we copy the data from the DDLC Poem Game wiki page<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a> and insert them into a CSV file. We then use the <code>read.csv()</code> function to import the data, maintaining that the column <code>word</code> is a character variable and not a factor. To preview the data, we apply the <code>kable</code> function fo the first five rows of the dataset, setting <code>booktabs = TRUE</code> so that we achieve a table with a clean look. The result is Table 1–see <em>Appendix A</em> for the full dataset.</p>
<div id="r-code-import" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> R Code: Import</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Import Dataset </span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="co">## Saved data from the following link into a CSV: https://ddlcwiki.net/wiki/Poem_game)</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;ddlc.csv&#39;</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)</span>
<span id="cb2-4"><a href="#cb2-4"></a></span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="co"># Show the first few rows of the dataset</span></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="kw">kable</span>(<span class="kw">head</span>(data, <span class="dv">5</span>), </span>
<span id="cb2-7"><a href="#cb2-7"></a>      <span class="dt">booktabs =</span> <span class="ot">TRUE</span>,</span>
<span id="cb2-8"><a href="#cb2-8"></a>      <span class="dt">caption =</span> <span class="st">&#39;DDLC Points Distribution Data (First Five Rows)&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;https://ddlcwiki.net/wiki/Poem_game&#39;</span>,</span>
<span id="cb2-11"><a href="#cb2-11"></a>           <span class="dt">general_title =</span> <span class="st">&#39;Data Source:&#39;</span>,</span>
<span id="cb2-12"><a href="#cb2-12"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:import">Table 2.1: </span>DDLC Points Distribution Data (First Five Rows)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Word
</th>
<th style="text-align:right;">
Sayori
</th>
<th style="text-align:right;">
Natsuki
</th>
<th style="text-align:right;">
Yuri
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
adventure
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
afterimage
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
agonizing
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
alone
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
amazing
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Data Source:</span> <sup></sup> <a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a>
</td>
</tr>
</tfoot>
</table>
</div>
</div>
</div>
<div id="results" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Results</h1>
<div id="overview-2" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Overview</h2>
<p>The purpose of this section is to demonstrate the results of the analysis based on the methodology provided. First, we examine the distribution of the points toward the characters. Next, we compare the central tendencies of the distributions for each of the characters. Then, we conduct ANOVA and Tukey HSD tests to determine whether there exists a statisitcally significant difference in the mean points among the characters, diagnosing the residuals afterward to know whether the residuals are normally distributed. Finally, after determining that the residuals are <em>not</em> normally distributed, I conduct the Kruskal-Wallis and Dunn’s Tests to conclude whether there truly is a statisitcally significant difference.</p>
</div>
<div id="distribution-of-points" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Distribution of Points</h2>
<p>To create Figure 1 (<em>Points Distribution in the DDLC Poem Minigame</em>), I pivot the original dataset into longform so that we have three columns: Words, Character, and Value–I do this procedure so that plotting the histograms by character could be done simultaneously rather than consequentially. Next, I create a theme called <code>theme_light2()</code>, which is a variation of ggplot2’s <code>theme_light()</code> such that the minor gridlines are removed, as well as the major x-axis ones. Finally, we use <code>ggplot()</code>, <code>geom_histogram()</code>, and <code>facet_wrap()</code> to plot the histograms of the points for each character. From these histograms in Figure 1, most words fall under the 1-point category for both Natsuki and Yuri; but for Sayori, most of her words fall in the 2-point category. Yuri receives the least amount of 2-point words and Natsuki the 3-point words. In contrast, with respect to the 3-point category, Sayori receives the most relative to Natsuki and Yuri. Overall, Sayori has the advantage in obtaining the most frequent 2- and 3-point words.</p>
<div id="r-code-distribution-of-points" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> R Code: Distribution of Points</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># Pivot the dataset.</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>data2 &lt;-<span class="st"> </span><span class="kw">gather</span>(data, <span class="st">&#39;Character&#39;</span>, <span class="st">&#39;Value&#39;</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">4</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># Create a function that sets up the background of the plot.</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>theme_light2 &lt;-<span class="st"> </span><span class="cf">function</span>() {</span>
<span id="cb3-6"><a href="#cb3-6"></a>  </span>
<span id="cb3-7"><a href="#cb3-7"></a>  <span class="kw">theme_light</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid.minor   =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb3-9"><a href="#cb3-9"></a>        <span class="dt">panel.grid.major.x =</span> <span class="kw">element_blank</span>())</span>
<span id="cb3-10"><a href="#cb3-10"></a>  </span>
<span id="cb3-11"><a href="#cb3-11"></a>}   </span>
<span id="cb3-12"><a href="#cb3-12"></a></span>
<span id="cb3-13"><a href="#cb3-13"></a><span class="co"># Generate the plot.</span></span>
<span id="cb3-14"><a href="#cb3-14"></a><span class="kw">ggplot</span>(data2) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-15"><a href="#cb3-15"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> Value, <span class="dt">fill =</span> Character) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-16"><a href="#cb3-16"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&#39;gray&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-17"><a href="#cb3-17"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Character) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-18"><a href="#cb3-18"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-19"><a href="#cb3-19"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x     =</span> <span class="st">&#39;Points&#39;</span>,</span>
<span id="cb3-20"><a href="#cb3-20"></a>       <span class="dt">y     =</span> <span class="st">&#39;Frequency&#39;</span>,</span>
<span id="cb3-21"><a href="#cb3-21"></a>       <span class="dt">title =</span> <span class="st">&#39;Fig. 1 - Points Distribution in the DDLC Poem Minigame&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-22"><a href="#cb3-22"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb3-23"><a href="#cb3-23"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span></code></pre></div>
<p><img src="DDLC_web-alt_files/figure-html/pdv-1.png" width="672" /></p>
</div>
</div>
<div id="central-tendency-of-the-points" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Central Tendency of the Points</h2>
<p>This subsection describes the central tendency of the distribution of the points for each character. Specifically, the individual means and standard deviations (SDs) are discussed, being compared to each other to determine whether there is a difference from a high-level view (i.e., to see whether the means are relatively similar or dissimilar without any statistical tests at this point). To assess the statistical significance among the means, the ANOVA results are presented in section 5.4.</p>
<p>To generate the central tendency of the points among the characters, we apply the <code>aggregate()</code> function and pass an anonymous function that uses <code>mean()</code> and <code>sd()</code> simultaneously; however, because the output of <code>aggregate()</code> in this form will nest the information, we execute <code>do.call(data.frame, l)</code>, where <code>l</code> is the aggregated list, to unnest the information. We then rename the columns so that they make more sense to the reader. Finally, we use <code>kable()</code> to generate the mean and SD table.</p>
<p>In this table, Natsuki has an average score of 1.855 +/- 0.819; Sayori has the highest average at 2.180 +/- 0.750; and Yuri has the least at 1.851 +/- 0.903 (Table 2; see Figure 2 for a bar-graph version). With respect to the overall mean, it is 1.962 +/- 0.839, which suggests that Sayori’s points maybe be inflating the overall mean–so to speak–due to her having the average points being more dissimilar to Natuski and Yuri than the reverse: in other words, while Natuski and Yuri have similar means that both round to 1.9, Sayori’s rounds to 2.2, which further suggests that the “true” mean–if the spread of points were under a uniform distribution–would be around 1.800.</p>
<div id="r-code-central-tendency-of-the-points" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> R Code: Central Tendency of the Points</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Calculate the mean and SDs of the points for each character.</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>msd &lt;-<span class="st"> </span><span class="kw">aggregate</span>(Value <span class="op">~</span><span class="st"> </span>Character, </span>
<span id="cb4-3"><a href="#cb4-3"></a>                 data2,</span>
<span id="cb4-4"><a href="#cb4-4"></a>                 <span class="cf">function</span>(x) <span class="kw">c</span>(<span class="dt">Mean =</span> <span class="kw">round</span>(<span class="kw">mean</span>(x), <span class="dv">3</span>), <span class="dt">SD =</span> <span class="kw">round</span>(<span class="kw">sd</span>(x), <span class="dv">3</span>))) <span class="op">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="st">  </span><span class="kw">do.call</span>(data.frame, .)</span>
<span id="cb4-6"><a href="#cb4-6"></a></span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="co"># Rename the columns.</span></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="kw">names</span>(msd) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Character&#39;</span>, <span class="st">&#39;Mean&#39;</span>, <span class="st">&#39;SD&#39;</span>)</span>
<span id="cb4-9"><a href="#cb4-9"></a></span>
<span id="cb4-10"><a href="#cb4-10"></a>msd <span class="op">%&lt;&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="st">  </span><span class="kw">rbind</span>(<span class="kw">data.frame</span>(<span class="dt">Character =</span> <span class="st">&#39;Overall&#39;</span>, </span>
<span id="cb4-12"><a href="#cb4-12"></a>                   <span class="dt">Mean      =</span> <span class="kw">round</span>(<span class="kw">mean</span>(data2<span class="op">$</span>Value), <span class="dv">3</span>),</span>
<span id="cb4-13"><a href="#cb4-13"></a>                   <span class="dt">SD        =</span> <span class="kw">round</span>(<span class="kw">sd</span>(data2<span class="op">$</span>Value), <span class="dv">3</span>)))</span>
<span id="cb4-14"><a href="#cb4-14"></a></span>
<span id="cb4-15"><a href="#cb4-15"></a><span class="co"># Show the means and standard deviations.</span></span>
<span id="cb4-16"><a href="#cb4-16"></a><span class="kw">kable</span>(msd, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Central Tendency of the Points&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb4-17"><a href="#cb4-17"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ctp">Table 3.1: </span>Central Tendency of the Points
</caption>
<thead>
<tr>
<th style="text-align:left;">
Character
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Natsuki
</td>
<td style="text-align:right;">
1.855
</td>
<td style="text-align:right;">
0.819
</td>
</tr>
<tr>
<td style="text-align:left;">
Sayori
</td>
<td style="text-align:right;">
2.180
</td>
<td style="text-align:right;">
0.750
</td>
</tr>
<tr>
<td style="text-align:left;">
Yuri
</td>
<td style="text-align:right;">
1.851
</td>
<td style="text-align:right;">
0.903
</td>
</tr>
<tr>
<td style="text-align:left;">
Overall
</td>
<td style="text-align:right;">
1.962
</td>
<td style="text-align:right;">
0.839
</td>
</tr>
</tbody>
</table>
</div>
<div id="r-code-central-tendency-of-the-points-bar-graph" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> R Code: Central Tendency of the Points Bar Graph</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Generate a plot of means and SDs.</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="kw">ggplot</span>(msd) <span class="op">+</span><span class="st"> </span></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> Character, <span class="dt">y =</span> Mean, <span class="dt">fill =</span> Character) <span class="op">+</span><span class="st"> </span></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&#39;identity&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb5-5"><a href="#cb5-5"></a><span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="dt">ymin =</span> msd<span class="op">$</span>Mean <span class="op">-</span><span class="st"> </span>msd<span class="op">$</span>SD, </span>
<span id="cb5-6"><a href="#cb5-6"></a>                <span class="dt">ymax =</span> msd<span class="op">$</span>Mean <span class="op">+</span><span class="st"> </span>msd<span class="op">$</span>SD,</span>
<span id="cb5-7"><a href="#cb5-7"></a>                <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span></span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(msd<span class="op">$</span>Mean), <span class="dt">lty =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb5-9"><a href="#cb5-9"></a><span class="st">  </span><span class="kw">ylim</span>(<span class="dv">0</span>, <span class="dv">3</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb5-10"><a href="#cb5-10"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;&#39;</span>,</span>
<span id="cb5-11"><a href="#cb5-11"></a>       <span class="dt">title =</span> <span class="st">&#39;Fig. 2 - Central Tendency of the Poem Minigame</span><span class="ch">\&#39;</span><span class="st">s </span></span>
<span id="cb5-12"><a href="#cb5-12"></a><span class="st">Points Distribution by DDLC Character&#39;</span>,</span>
<span id="cb5-13"><a href="#cb5-13"></a>       <span class="dt">caption =</span> <span class="st">&#39;Note: The error bars (i.e. the &quot;I&quot; geometries) </span></span>
<span id="cb5-14"><a href="#cb5-14"></a><span class="st">indicate the standard deviation of a specific character</span><span class="ch">\&#39;</span><span class="st">s distribution,</span></span>
<span id="cb5-15"><a href="#cb5-15"></a><span class="st">centered at a character</span><span class="ch">\&#39;</span><span class="st">s average number of points across the words.</span></span>
<span id="cb5-16"><a href="#cb5-16"></a><span class="st">Dashed line indicates the grand mean across the characters.&#39;</span>) <span class="op">+</span></span>
<span id="cb5-17"><a href="#cb5-17"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">fill =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb5-18"><a href="#cb5-18"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span></code></pre></div>
<p><img src="DDLC_web-alt_files/figure-html/ctp2-1.png" width="672" /></p>
</div>
</div>
<div id="anova" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> ANOVA</h2>
<p>The ANOVA model tests whether there exists an overall statistically significant difference in the means among Natsuki, Sayori, and Yuri. This idea is important on the basis that there should <em>not</em> be a statistically significant difference if the spread of the points follow a uniform distribution. However, as noted in the previous subsection 5.3, the means and SDs are not uniform across the characters. Therefore, the ANOVA will assess this observation, being followed by a Tukey HSD test to examine pairwise-mean tests to see where the difference occurs.</p>
<p>To estimate the ANOVA models in R, we employ the <code>aov()</code> function. Then we convert the results into a dataframe using the <code>tidy()</code> function from the <code>broom</code> library, rounding the results to three significant digits. Then after adjusting the column names to be more understandable of what the statistical metrics are to the reader, we use the <code>kable()</code> function to produce Tables 3 and 4. Based on these tables, there exists a statistically significant difference among the means ((<span class="math inline">\(F_1\)</span>, <span class="math inline">\(p_1\)</span>)) = (11.891, &lt; 0.001) and (<span class="math inline">\(F_2\)</span>, <span class="math inline">\(p_2\)</span>) = (15.184, &lt; 0.001) respectively). To test where the specific difference occurs, we conduct the Tukey HSD test.</p>
<div id="r-code-anova-models" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> R Code: ANOVA Models</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Estimate ANOVA.</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>anova1 &lt;-<span class="st"> </span><span class="kw">aov</span>(Value <span class="op">~</span><span class="st"> </span>Character, data2)</span>
<span id="cb6-3"><a href="#cb6-3"></a>anova2 &lt;-<span class="st"> </span><span class="kw">aov</span>(<span class="kw">log</span>(Value) <span class="op">~</span><span class="st"> </span>Character, data2)</span>
<span id="cb6-4"><a href="#cb6-4"></a></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="co"># &quot;Tidy&quot; ANOVA (i.e. convert results into a data frame).</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>anova1_tidy &lt;-<span class="st"> </span><span class="kw">tidy</span>(anova1)</span>
<span id="cb6-7"><a href="#cb6-7"></a>anova2_tidy &lt;-<span class="st"> </span><span class="kw">tidy</span>(anova2)</span>
<span id="cb6-8"><a href="#cb6-8"></a></span>
<span id="cb6-9"><a href="#cb6-9"></a><span class="co"># Round results to three significant digits.</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>anova1_tidy[, <span class="dv">3</span><span class="op">:</span><span class="dv">6</span>] <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">3</span>)</span>
<span id="cb6-11"><a href="#cb6-11"></a>anova2_tidy[, <span class="dv">3</span><span class="op">:</span><span class="dv">6</span>] <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">3</span>)</span>
<span id="cb6-12"><a href="#cb6-12"></a></span>
<span id="cb6-13"><a href="#cb6-13"></a><span class="co"># Rename columns so that they are understandable.</span></span>
<span id="cb6-14"><a href="#cb6-14"></a><span class="kw">names</span>(anova1_tidy) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Term&#39;</span>, <span class="st">&#39;DF&#39;</span>, <span class="st">&#39;Sum of Squares&#39;</span>,</span>
<span id="cb6-15"><a href="#cb6-15"></a>                        <span class="st">&#39;Mean Square&#39;</span>, <span class="st">&#39;F&#39;</span>, <span class="st">&#39;p&#39;</span>)</span>
<span id="cb6-16"><a href="#cb6-16"></a></span>
<span id="cb6-17"><a href="#cb6-17"></a><span class="kw">names</span>(anova2_tidy) &lt;-<span class="st"> </span><span class="kw">names</span>(anova1_tidy)</span>
<span id="cb6-18"><a href="#cb6-18"></a></span>
<span id="cb6-19"><a href="#cb6-19"></a><span class="co"># ANOVA 1</span></span>
<span id="cb6-20"><a href="#cb6-20"></a><span class="kw">kable</span>(anova1_tidy, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;ANOVA Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb6-21"><a href="#cb6-21"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb6-22"><a href="#cb6-22"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;DF = Degrees of Freedom.&#39;</span>,</span>
<span id="cb6-23"><a href="#cb6-23"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:stats1, miss)ANOVA Results
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
DF
</th>
<th style="text-align:right;">
Sum of Squares
</th>
<th style="text-align:right;">
Mean Square
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Character
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
16.231
</td>
<td style="text-align:right;">
8.115
</td>
<td style="text-align:right;">
11.891
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
681
</td>
<td style="text-align:right;">
464.781
</td>
<td style="text-align:right;">
0.682
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> DF = Degrees of Freedom.
</td>
</tr>
</tfoot>
</table>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># ANOVA 2</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="kw">kable</span>(anova2_tidy, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Log ANOVA Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;DF = Degrees of Freedom.&#39;</span>,</span>
<span id="cb7-5"><a href="#cb7-5"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:stats1, miss)Log ANOVA Results
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
DF
</th>
<th style="text-align:right;">
Sum of Squares
</th>
<th style="text-align:right;">
Mean Square
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Character
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6.373
</td>
<td style="text-align:right;">
3.187
</td>
<td style="text-align:right;">
15.184
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
681
</td>
<td style="text-align:right;">
142.924
</td>
<td style="text-align:right;">
0.210
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> DF = Degrees of Freedom.
</td>
</tr>
</tfoot>
</table>
</div>
</div>
<div id="tukey-hsd" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Tukey HSD</h2>
<p>To conduct the Tukey HSD test to examine pairwise-mean comparisons in R, we use the <code>TukeyHSD()</code> function. After employing it and rounding the values to three significant digits, we rename the colukmns so that the metrics are understandable to the reader. We then use <code>kable()</code> to produce Tables 5 and 6.</p>
<p>In Table 5, the difference in means between Sayori and Natsuki is 0.325 and is statistically significant(CI = [0.143, 0.506], p &lt; 0.001). In contrast to the stark difference, Yuri and Natsuki’s difference in means is -0.004 and not statistically significant (CI = [-0.186, 0.177], p = 0.998). Between Yuri and Sayori, the difference in means is -0.329 and is statistically significant (CI = [-0.511, -0.147], p &lt; 0.001). In turn, Sayori statistically has greater means than Natuski and Yuri at the 5% margin-of-error level.</p>
<p>In Table 6, the difference in log means between Sayori and Natsuki is 0.192 and is statistically significant (CI = [0.091, 0.293], p &lt; 0.001). Inversely, Yuri and Natsuki’s difference in log means is -0.023 and is not statistically significant (CI = [-0.124, 0.078], p = 0.851). Between Yuri and Sayori, the difference in log means is -0.215 (CI = [-0.316, -0.115], p &lt; 0.001). In turn, Sayori statistically has greater means than Natuski and Yuri at the 5% margin-of-error level.</p>
<div id="r-code-tukey-hsd-tests" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> R Code: Tukey HSD Tests</h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># Obtain the Tukey HSD results</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>th1 &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">TukeyHSD</span>(anova1)<span class="op">$</span>Character, <span class="dv">3</span>)</span>
<span id="cb8-3"><a href="#cb8-3"></a>th2 &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">TukeyHSD</span>(anova2)<span class="op">$</span>Character, <span class="dv">3</span>)</span>
<span id="cb8-4"><a href="#cb8-4"></a></span>
<span id="cb8-5"><a href="#cb8-5"></a><span class="co"># Rename the columns</span></span>
<span id="cb8-6"><a href="#cb8-6"></a><span class="kw">colnames</span>(th1) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Difference in Means&#39;</span>, <span class="st">&#39;Lower CI Bound&#39;</span>, <span class="st">&#39;Upper CI Bound&#39;</span>, </span>
<span id="cb8-7"><a href="#cb8-7"></a>                   <span class="st">&#39;Adjusted p-value&#39;</span>)</span>
<span id="cb8-8"><a href="#cb8-8"></a></span>
<span id="cb8-9"><a href="#cb8-9"></a><span class="kw">colnames</span>(th2) &lt;-<span class="st"> </span><span class="kw">colnames</span>(th1)</span>
<span id="cb8-10"><a href="#cb8-10"></a></span>
<span id="cb8-11"><a href="#cb8-11"></a><span class="co"># Display the Tukey HSD results.</span></span>
<span id="cb8-12"><a href="#cb8-12"></a></span>
<span id="cb8-13"><a href="#cb8-13"></a><span class="co">## Tukey HSD 1</span></span>
<span id="cb8-14"><a href="#cb8-14"></a><span class="kw">kable</span>(th1, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Tukey HSD Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb8-15"><a href="#cb8-15"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb8-16"><a href="#cb8-16"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;CI = Confidence Interval&#39;</span>,</span>
<span id="cb8-17"><a href="#cb8-17"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:stats2">Table 3.2: </span>Tukey HSD Results
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Difference in Means
</th>
<th style="text-align:right;">
Lower CI Bound
</th>
<th style="text-align:right;">
Upper CI Bound
</th>
<th style="text-align:right;">
Adjusted p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Sayori-Natsuki
</td>
<td style="text-align:right;">
0.325
</td>
<td style="text-align:right;">
0.143
</td>
<td style="text-align:right;">
0.506
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Yuri-Natsuki
</td>
<td style="text-align:right;">
-0.004
</td>
<td style="text-align:right;">
-0.186
</td>
<td style="text-align:right;">
0.177
</td>
<td style="text-align:right;">
0.998
</td>
</tr>
<tr>
<td style="text-align:left;">
Yuri-Sayori
</td>
<td style="text-align:right;">
-0.329
</td>
<td style="text-align:right;">
-0.511
</td>
<td style="text-align:right;">
-0.147
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> CI = Confidence Interval
</td>
</tr>
</tfoot>
</table>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co">## Tukey HSD 2</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="kw">kable</span>(th2, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Log Tukey HSD Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;CI = Confidence Interval&#39;</span>,</span>
<span id="cb9-5"><a href="#cb9-5"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:stats2">Table 3.2: </span>Log Tukey HSD Results
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Difference in Means
</th>
<th style="text-align:right;">
Lower CI Bound
</th>
<th style="text-align:right;">
Upper CI Bound
</th>
<th style="text-align:right;">
Adjusted p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Sayori-Natsuki
</td>
<td style="text-align:right;">
0.192
</td>
<td style="text-align:right;">
0.091
</td>
<td style="text-align:right;">
0.293
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Yuri-Natsuki
</td>
<td style="text-align:right;">
-0.023
</td>
<td style="text-align:right;">
-0.124
</td>
<td style="text-align:right;">
0.078
</td>
<td style="text-align:right;">
0.851
</td>
</tr>
<tr>
<td style="text-align:left;">
Yuri-Sayori
</td>
<td style="text-align:right;">
-0.215
</td>
<td style="text-align:right;">
-0.316
</td>
<td style="text-align:right;">
-0.115
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span> <sup></sup> CI = Confidence Interval
</td>
</tr>
</tfoot>
</table>
</div>
</div>
<div id="anova-residual-diagnostics" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> ANOVA Residual Diagnostics</h2>
<p>The purpose of this subsection is to diagnose the residuals from the ANOVA model to determine whether an additional test is needed if the residuals do not follow a normal distribution. To do so, we first set up a data frame of predicted values and residuals from the two ANOVA models (the non-logged and logged versions). Then We generate histograms for both of them. As such, based on Figures 3 and 4, the residuals do not resemble a normal distribution: upon examination, they seem to have a bimodal distribution with an emphasis on the negative side (in other words, skewed left), suggesting that a non-parametric test is required to truly test the means between the characters–the Kruskal-Wallis test is performed in the next subsetcion.</p>
<div id="r-code-residuals-setup" class="section level3" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> R Code: Residuals Setup</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># Obtain residuals and predicted values.</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>fitres &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">fit1 =</span> <span class="kw">predict</span>(anova1),</span>
<span id="cb10-3"><a href="#cb10-3"></a>                     <span class="dt">res1 =</span> <span class="kw">resid</span>(anova1),</span>
<span id="cb10-4"><a href="#cb10-4"></a>                     <span class="dt">fit2 =</span> <span class="kw">predict</span>(anova2),</span>
<span id="cb10-5"><a href="#cb10-5"></a>                     <span class="dt">res2 =</span> <span class="kw">resid</span>(anova2))</span></code></pre></div>
</div>
<div id="r-code-residuals-distributions" class="section level3" number="3.6.2">
<h3><span class="header-section-number">3.6.2</span> R Code: Residuals Distributions</h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>fr1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(fitres) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> res1) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">15</span>, <span class="dt">fill =</span> <span class="st">&#39;cyan4&#39;</span>, <span class="dt">col =</span> <span class="st">&#39;gray&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&#39;Frequency&#39;</span>,</span>
<span id="cb11-5"><a href="#cb11-5"></a>       <span class="dt">x =</span> <span class="st">&#39;Residuals&#39;</span>,</span>
<span id="cb11-6"><a href="#cb11-6"></a>       <span class="dt">title =</span> <span class="st">&#39;Fig. 3 - Residuals Distribution&#39;</span>) <span class="op">+</span></span>
<span id="cb11-7"><a href="#cb11-7"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span>
<span id="cb11-8"><a href="#cb11-8"></a></span>
<span id="cb11-9"><a href="#cb11-9"></a>fr2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(fitres) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-10"><a href="#cb11-10"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">x =</span> res2) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-11"><a href="#cb11-11"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">15</span>, <span class="dt">fill =</span> <span class="st">&#39;cyan4&#39;</span>, <span class="dt">col =</span> <span class="st">&#39;gray&#39;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb11-12"><a href="#cb11-12"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&#39;&#39;</span>,</span>
<span id="cb11-13"><a href="#cb11-13"></a>       <span class="dt">x =</span> <span class="st">&#39;Log Residuals&#39;</span>,       </span>
<span id="cb11-14"><a href="#cb11-14"></a>       <span class="dt">title =</span> <span class="st">&#39;Fig. 4 - Log Residuals Distribution&#39;</span>) <span class="op">+</span></span>
<span id="cb11-15"><a href="#cb11-15"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span>
<span id="cb11-16"><a href="#cb11-16"></a></span>
<span id="cb11-17"><a href="#cb11-17"></a><span class="kw">grid.arrange</span>(fr1, fr2, <span class="dt">nrow =</span> <span class="dv">1</span>, <span class="dt">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="DDLC_web-alt_files/figure-html/hr-1.png" width="768" /></p>
</div>
</div>
<div id="kruskal-wallis-test" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> Kruskal-Wallis Test</h2>
<p>To conduct the Kruskal-Wallist test, we employ the <code>kruskal.test()</code> function, “tidying” the output so that they are in a clean data frame to be able to produce a <code>kable</code> table. Based on Table 7, there is a statistically significant difference among the characters’ mean scores (test statistic = 23.732, p &lt; 0.001). To know whether the pairwise means are statistically significant, Dunn’s Test must be performed.</p>
<div id="r-code-kruskal-wallis-test" class="section level3" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> R Code: Kruskal-Wallis Test</h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>kw &lt;-<span class="st"> </span><span class="kw">tidy</span>(<span class="kw">kruskal.test</span>(Value <span class="op">~</span><span class="st"> </span>Character, data2))</span>
<span id="cb12-2"><a href="#cb12-2"></a></span>
<span id="cb12-3"><a href="#cb12-3"></a>kw[, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>] <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">3</span>)</span>
<span id="cb12-4"><a href="#cb12-4"></a></span>
<span id="cb12-5"><a href="#cb12-5"></a><span class="kw">kable</span>(kw, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Kruskal-Wallis Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:kw">Table 3.3: </span>Kruskal-Wallis Results
</caption>
<thead>
<tr>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
parameter
</th>
<th style="text-align:left;">
method
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
23.732
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Kruskal-Wallis rank sum test
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="dunn-test" class="section level2" number="3.8">
<h2><span class="header-section-number">3.8</span> Dunn Test</h2>
<p>To conduct Dunn’s Test, <code>dunnTest()</code> from the <code>FSA</code> library is used. Based on Table 8, the difference between Nastuki and Sayori (Z = -4.163, p &lt; 0.001) and between Sayori and Yuri (Z = 4.273, p &lt; 0.001) are statistically significant, whereas the difference between Natsuki an dYuri is not (Z = 0.110, p = 0.913). This finding indicates that Sayori has a statistically significantly higher mean than the other two characters, which further implies a statistical bias towards Sayori in the Poem Minigame.</p>
<div id="r-code-dunn-test" class="section level3" number="3.8.1">
<h3><span class="header-section-number">3.8.1</span> R Code: Dunn Test</h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>dt &lt;-<span class="st"> </span><span class="kw">dunnTest</span>(Value <span class="op">~</span><span class="st"> </span>Character, data2, <span class="dt">method =</span> <span class="st">&#39;bh&#39;</span>)<span class="op">$</span>res <span class="op">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span>
<span id="cb13-3"><a href="#cb13-3"></a></span>
<span id="cb13-4"><a href="#cb13-4"></a><span class="kw">names</span>(dt) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Comparison&#39;</span>, <span class="st">&#39;Z&#39;</span>, <span class="st">&#39;Unadjusted p-value&#39;</span>,</span>
<span id="cb13-5"><a href="#cb13-5"></a>               <span class="st">&#39;Adjusted p-value&#39;</span>)</span>
<span id="cb13-6"><a href="#cb13-6"></a></span>
<span id="cb13-7"><a href="#cb13-7"></a>dt[, <span class="dv">2</span><span class="op">:</span><span class="dv">4</span>] <span class="op">%&lt;&gt;%</span><span class="st"> </span><span class="kw">round</span>(., <span class="dv">3</span>)</span>
<span id="cb13-8"><a href="#cb13-8"></a></span>
<span id="cb13-9"><a href="#cb13-9"></a><span class="kw">kable</span>(dt, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&#39;Dunn Test Results&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="st">&quot;hold_position&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dt">Table 3.4: </span>Dunn Test Results
</caption>
<thead>
<tr>
<th style="text-align:left;">
Comparison
</th>
<th style="text-align:right;">
Z
</th>
<th style="text-align:right;">
Unadjusted p-value
</th>
<th style="text-align:right;">
Adjusted p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Natsuki - Sayori
</td>
<td style="text-align:right;">
-4.163
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Natsuki - Yuri
</td>
<td style="text-align:right;">
0.110
</td>
<td style="text-align:right;">
0.913
</td>
<td style="text-align:right;">
0.913
</td>
</tr>
<tr>
<td style="text-align:left;">
Sayori - Yuri
</td>
<td style="text-align:right;">
4.273
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="conclusion" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Conclusion</h1>
<div id="discussion" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Discussion</h2>
<p>Some may argue that Poem Minigame is simply a ruse with no inherent underlying meaning nor use. However, the results of this study show that the bias in the Poem Minigame is towards Sayori (2.180 +/- 0.819 vs. overall mean of 1.962 +/- 0.839), who is the first character in the game to experience a traumatic outcome, implying that the statistical aspect of the minigame may have geared the player towards her to emphasize the emotional impact of the end of Act 1. After all, if a character receives the most points, the game plays additional, intimate scenes with said character, which increases the player’s affability to her. Thus, the ending of Act 1 would be more heart-wrenching than if the words in the poem minigame were more fairly weighted (i.e. the points being weighted in a way such that each character would have an equal chance of receiving points).</p>
</div>
<div id="limitations" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Limitations</h2>
<p>Despite the robust tests presented in this paper, there are a number of limitations. Namely, this paper assumes that the probability of each word in the minigame being selected by the player is weighted equally (i.e. a uniform probability distribution of the words). In DDLC, 10 words are presented in each round, so the probabilities may be shifted per round and as such may affect one of the assumptions in the ANOVA models. Future work may take this issue into account by emploiying a Monte Carlo simulation to test multiple ANOVA outcomes.</p>
<p>A second limitation is that there is little-to-no literature examining the statistical components of DDLC. As such, knowledge regarding them are sparse if not non-existent. Nonetheless, the results presented in this paper should serve as a baseline for further research.</p>
</div>
</div>
<div id="references" class="section level1 unnumbered" number="">
<h1>References</h1>
<p>Corder, Gregory and Dale Foreman (2009). Nonparametric Statistics for Non-Statisticians. <em>Hoboken: John Wiley &amp; Sons.</em> p. 99-105.</p>
<p>Doki Doki Literature Club. <a href="https://ddlc.moe/" class="uri">https://ddlc.moe/</a>. Accessed 1/20/2020.</p>
<p>Doki Doki Literature Club Wiki. <em>Poem Game</em>. <a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a>. Accessed 1/20/2020.</p>
<p>Dokiu Doki Literature Club Wiki. <em>Act 1</em>. <a href="https://doki-doki-literature-club.fandom.com/wiki/Act_1" class="uri">https://doki-doki-literature-club.fandom.com/wiki/Act_1</a>. Accessed 1/20/2020.</p>
<p>Dunn, Olive Jean (1964). Multiple comparisons using rank sums. <em>Technometrics</em>: 6(3): 241-252.</p>
<p>Neri, David (2018). An Examination of Western Romance/Horror Hybrid Visual Novels commentary on traditional Eastern VN Romance Tropes. <em>ReVisions</em>. <a href="https://revisions.pubpub.org/pub/odpf39ub" class="uri">https://revisions.pubpub.org/pub/odpf39ub</a>. Accessed 1/20/2020.</p>
<p>Ogle, D.H., P. Wheeler, and A. Dinno (2019). FSA: Fisheries Stock Analysis. R package version 0.8.26, <a href="https://github.com/droglenc/FSA" class="uri">https://github.com/droglenc/FSA</a>.</p>
<p>Roe, Curie and Alex Mitchell (2019). “Is This Really Happening?”: Game Mechanics as Unreliable Narrator. <em>Digital Games Research Association</em>. <em>Proceedings of DiGRA 2019</em>.</p>
</div>
<div id="appendix-a---full-dataset" class="section level1 unnumbered" number="">
<h1>Appendix A - Full Dataset</h1>
<div id="r-code-full-dataset" class="section level3 unnumbered" number="">
<h3>R Code: Full Dataset</h3>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="kw">kable</span>(data, </span>
<span id="cb14-2"><a href="#cb14-2"></a>      <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, </span>
<span id="cb14-3"><a href="#cb14-3"></a>      <span class="dt">longtable =</span> <span class="ot">TRUE</span>, </span>
<span id="cb14-4"><a href="#cb14-4"></a>      <span class="dt">caption =</span> <span class="st">&#39;DDLC Points Distribution Data&#39;</span>,</span>
<span id="cb14-5"><a href="#cb14-5"></a>      <span class="dt">row.names =</span> <span class="ot">TRUE</span>,</span>
<span id="cb14-6"><a href="#cb14-6"></a>      <span class="dt">linesep =</span> <span class="st">&#39;&#39;</span>) <span class="op">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>, <span class="dt">latex_options =</span> <span class="kw">c</span>(<span class="st">&#39;repeat_header&#39;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&#39;https://ddlcwiki.net/wiki/Poem_game&#39;</span>,</span>
<span id="cb14-9"><a href="#cb14-9"></a>           <span class="dt">general_title =</span> <span class="st">&#39;Data Source:&#39;</span>,</span>
<span id="cb14-10"><a href="#cb14-10"></a>           <span class="dt">footnote_as_chunk =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:appendixA">Table 4.1: </span>DDLC Points Distribution Data
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Word
</th>
<th style="text-align:right;">
Sayori
</th>
<th style="text-align:right;">
Natsuki
</th>
<th style="text-align:right;">
Yuri
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
adventure
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
afterimage
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
agonizing
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
alone
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
amazing
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
ambient
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
analysis
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:left;">
anger
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
anime
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
anxiety
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
atone
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
aura
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
awesome
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
14
</td>
<td style="text-align:left;">
beauty
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:left;">
bed
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
16
</td>
<td style="text-align:left;">
blanket
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
17
</td>
<td style="text-align:left;">
bliss
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
boop
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
bouncy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
20
</td>
<td style="text-align:left;">
breathe
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
21
</td>
<td style="text-align:left;">
broken
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
bubbles
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
23
</td>
<td style="text-align:left;">
bunny
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
cage
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
25
</td>
<td style="text-align:left;">
calm
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
26
</td>
<td style="text-align:left;">
candy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
27
</td>
<td style="text-align:left;">
captive
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
28
</td>
<td style="text-align:left;">
charm
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
29
</td>
<td style="text-align:left;">
cheeks
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
30
</td>
<td style="text-align:left;">
cheer
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
31
</td>
<td style="text-align:left;">
childhood
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
32
</td>
<td style="text-align:left;">
chocolate
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
33
</td>
<td style="text-align:left;">
climax
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
34
</td>
<td style="text-align:left;">
clouds
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
35
</td>
<td style="text-align:left;">
clumsy
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
36
</td>
<td style="text-align:left;">
color
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
37
</td>
<td style="text-align:left;">
comfort
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
38
</td>
<td style="text-align:left;">
contamination
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
39
</td>
<td style="text-align:left;">
covet
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
40
</td>
<td style="text-align:left;">
crimson
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
41
</td>
<td style="text-align:left;">
cry
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
42
</td>
<td style="text-align:left;">
cute
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
43
</td>
<td style="text-align:left;">
dance
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
44
</td>
<td style="text-align:left;">
dark
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
45
</td>
<td style="text-align:left;">
daydream
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
46
</td>
<td style="text-align:left;">
dazzle
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
47
</td>
<td style="text-align:left;">
death
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
48
</td>
<td style="text-align:left;">
defeat
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
49
</td>
<td style="text-align:left;">
depression
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
50
</td>
<td style="text-align:left;">
desire
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
51
</td>
<td style="text-align:left;">
despise
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
52
</td>
<td style="text-align:left;">
destiny
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
53
</td>
<td style="text-align:left;">
determination
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
54
</td>
<td style="text-align:left;">
disarray
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
55
</td>
<td style="text-align:left;">
disaster
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
56
</td>
<td style="text-align:left;">
disoriented
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
57
</td>
<td style="text-align:left;">
disown
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
58
</td>
<td style="text-align:left;">
doki-doki
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
59
</td>
<td style="text-align:left;">
dream
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
60
</td>
<td style="text-align:left;">
effulgent
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
61
</td>
<td style="text-align:left;">
electricity
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
62
</td>
<td style="text-align:left;">
email
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
63
</td>
<td style="text-align:left;">
embrace
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
64
</td>
<td style="text-align:left;">
empty
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
65
</td>
<td style="text-align:left;">
entropy
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
66
</td>
<td style="text-align:left;">
essence
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
67
</td>
<td style="text-align:left;">
eternity
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
68
</td>
<td style="text-align:left;">
excitement
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
69
</td>
<td style="text-align:left;">
existence
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
70
</td>
<td style="text-align:left;">
explode
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
71
</td>
<td style="text-align:left;">
extraordinary
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
72
</td>
<td style="text-align:left;">
extreme
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
73
</td>
<td style="text-align:left;">
family
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
74
</td>
<td style="text-align:left;">
fantasy
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
75
</td>
<td style="text-align:left;">
fear
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
76
</td>
<td style="text-align:left;">
feather
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
77
</td>
<td style="text-align:left;">
fester
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
78
</td>
<td style="text-align:left;">
fickle
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
79
</td>
<td style="text-align:left;">
fireflies
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
80
</td>
<td style="text-align:left;">
fireworks
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
81
</td>
<td style="text-align:left;">
flee
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
82
</td>
<td style="text-align:left;">
flower
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
83
</td>
<td style="text-align:left;">
fluffy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
84
</td>
<td style="text-align:left;">
flying
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
85
</td>
<td style="text-align:left;">
forgive
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
86
</td>
<td style="text-align:left;">
friends
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
87
</td>
<td style="text-align:left;">
frightening
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
88
</td>
<td style="text-align:left;">
fun
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
89
</td>
<td style="text-align:left;">
games
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
90
</td>
<td style="text-align:left;">
giggle
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
91
</td>
<td style="text-align:left;">
graveyard
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
92
</td>
<td style="text-align:left;">
grief
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
93
</td>
<td style="text-align:left;">
hair
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
94
</td>
<td style="text-align:left;">
happiness
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
95
</td>
<td style="text-align:left;">
headphones
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
96
</td>
<td style="text-align:left;">
heartbeat
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
97
</td>
<td style="text-align:left;">
heart
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
98
</td>
<td style="text-align:left;">
heavensent
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
99
</td>
<td style="text-align:left;">
holiday
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
100
</td>
<td style="text-align:left;">
hopeless
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
101
</td>
<td style="text-align:left;">
hope
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
102
</td>
<td style="text-align:left;">
hop
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
103
</td>
<td style="text-align:left;">
horror
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
104
</td>
<td style="text-align:left;">
hurt
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
105
</td>
<td style="text-align:left;">
imagination
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
106
</td>
<td style="text-align:left;">
incapable
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
107
</td>
<td style="text-align:left;">
incongruent
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
108
</td>
<td style="text-align:left;">
infallible
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
109
</td>
<td style="text-align:left;">
inferno
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
110
</td>
<td style="text-align:left;">
infinite
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
111
</td>
<td style="text-align:left;">
insight
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
112
</td>
<td style="text-align:left;">
intellectual
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
113
</td>
<td style="text-align:left;">
journey
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
114
</td>
<td style="text-align:left;">
joy
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
115
</td>
<td style="text-align:left;">
judgment
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
116
</td>
<td style="text-align:left;">
jumpy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
117
</td>
<td style="text-align:left;">
jump
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
118
</td>
<td style="text-align:left;">
kawaii
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
119
</td>
<td style="text-align:left;">
kiss
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
120
</td>
<td style="text-align:left;">
kitty
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
121
</td>
<td style="text-align:left;">
landscape
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
122
</td>
<td style="text-align:left;">
laugh
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
123
</td>
<td style="text-align:left;">
lazy
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
124
</td>
<td style="text-align:left;">
lipstick
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
125
</td>
<td style="text-align:left;">
lollipop
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
126
</td>
<td style="text-align:left;">
loud
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
127
</td>
<td style="text-align:left;">
love
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
128
</td>
<td style="text-align:left;">
lucky
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
129
</td>
<td style="text-align:left;">
lust
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
130
</td>
<td style="text-align:left;">
marriage
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
131
</td>
<td style="text-align:left;">
marshmallow
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
132
</td>
<td style="text-align:left;">
massacre
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
133
</td>
<td style="text-align:left;">
meager
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
134
</td>
<td style="text-align:left;">
melancholy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
135
</td>
<td style="text-align:left;">
melody
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
136
</td>
<td style="text-align:left;">
memories
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
137
</td>
<td style="text-align:left;">
milk
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
138
</td>
<td style="text-align:left;">
misery
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
139
</td>
<td style="text-align:left;">
misfortune
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
140
</td>
<td style="text-align:left;">
mouse
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
141
</td>
<td style="text-align:left;">
music
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
142
</td>
<td style="text-align:left;">
nature
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
143
</td>
<td style="text-align:left;">
nibble
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
144
</td>
<td style="text-align:left;">
nightgown
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
145
</td>
<td style="text-align:left;">
ocean
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
146
</td>
<td style="text-align:left;">
pain
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
147
</td>
<td style="text-align:left;">
papa
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
148
</td>
<td style="text-align:left;">
parfait
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
149
</td>
<td style="text-align:left;">
party
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
150
</td>
<td style="text-align:left;">
passion
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
151
</td>
<td style="text-align:left;">
peaceful
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
152
</td>
<td style="text-align:left;">
peace
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
153
</td>
<td style="text-align:left;">
philosophy
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
pink
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
155
</td>
<td style="text-align:left;">
playground
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
156
</td>
<td style="text-align:left;">
play
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
157
</td>
<td style="text-align:left;">
pleasure
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
158
</td>
<td style="text-align:left;">
poof
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
159
</td>
<td style="text-align:left;">
portrait
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
160
</td>
<td style="text-align:left;">
pout
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
161
</td>
<td style="text-align:left;">
prayer
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
162
</td>
<td style="text-align:left;">
precious
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
163
</td>
<td style="text-align:left;">
promise
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
164
</td>
<td style="text-align:left;">
puppy
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
165
</td>
<td style="text-align:left;">
pure
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
166
</td>
<td style="text-align:left;">
question
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
167
</td>
<td style="text-align:left;">
rainbow
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
168
</td>
<td style="text-align:left;">
raincloud
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
169
</td>
<td style="text-align:left;">
raindrops
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
170
</td>
<td style="text-align:left;">
ribbon
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
171
</td>
<td style="text-align:left;">
romance
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
172
</td>
<td style="text-align:left;">
rose
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
173
</td>
<td style="text-align:left;">
sadness
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
174
</td>
<td style="text-align:left;">
scars
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
175
</td>
<td style="text-align:left;">
secretive
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
176
</td>
<td style="text-align:left;">
sensation
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
177
</td>
<td style="text-align:left;">
shame
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
178
</td>
<td style="text-align:left;">
shiny
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
179
</td>
<td style="text-align:left;">
shopping
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
180
</td>
<td style="text-align:left;">
silly
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
181
</td>
<td style="text-align:left;">
sing
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
182
</td>
<td style="text-align:left;">
skipping
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
183
</td>
<td style="text-align:left;">
skirt
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
184
</td>
<td style="text-align:left;">
smile
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
185
</td>
<td style="text-align:left;">
socks
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
186
</td>
<td style="text-align:left;">
sparkle
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
187
</td>
<td style="text-align:left;">
special
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
188
</td>
<td style="text-align:left;">
spinning
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
189
</td>
<td style="text-align:left;">
starscape
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
190
</td>
<td style="text-align:left;">
sticky
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
191
</td>
<td style="text-align:left;">
strawberry
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
192
</td>
<td style="text-align:left;">
sugar
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
193
</td>
<td style="text-align:left;">
suicide
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
194
</td>
<td style="text-align:left;">
summer
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
195
</td>
<td style="text-align:left;">
sunny
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
196
</td>
<td style="text-align:left;">
sunset
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
197
</td>
<td style="text-align:left;">
sweet
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
198
</td>
<td style="text-align:left;">
swimsuit
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
199
</td>
<td style="text-align:left;">
tears
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
200
</td>
<td style="text-align:left;">
tenacious
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
201
</td>
<td style="text-align:left;">
time
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
202
</td>
<td style="text-align:left;">
together
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
203
</td>
<td style="text-align:left;">
tragedy
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
204
</td>
<td style="text-align:left;">
treasure
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
205
</td>
<td style="text-align:left;">
twirl
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
206
</td>
<td style="text-align:left;">
uncanny
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
207
</td>
<td style="text-align:left;">
uncontrollable
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
208
</td>
<td style="text-align:left;">
unending
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
209
</td>
<td style="text-align:left;">
universe
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
210
</td>
<td style="text-align:left;">
unrequited
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
211
</td>
<td style="text-align:left;">
unrestrained
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
212
</td>
<td style="text-align:left;">
unstable
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
213
</td>
<td style="text-align:left;">
vacation
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
214
</td>
<td style="text-align:left;">
valentine
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
215
</td>
<td style="text-align:left;">
vanilla
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
216
</td>
<td style="text-align:left;">
variance
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
217
</td>
<td style="text-align:left;">
vertigo
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
218
</td>
<td style="text-align:left;">
vibrant
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
219
</td>
<td style="text-align:left;">
vitality
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
220
</td>
<td style="text-align:left;">
vivacious
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
221
</td>
<td style="text-align:left;">
vivid
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
222
</td>
<td style="text-align:left;">
warm
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
223
</td>
<td style="text-align:left;">
waterfall
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
224
</td>
<td style="text-align:left;">
whirlwind
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
225
</td>
<td style="text-align:left;">
whisper
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
226
</td>
<td style="text-align:left;">
whistle
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
227
</td>
<td style="text-align:left;">
wonderful
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
228
</td>
<td style="text-align:left;">
wrath
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Data Source:</span> <sup></sup> <a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a>
</td>
</tr>
</tfoot>
</table>
</div>
</div>
<div id="appendix-b---scatter-plots" class="section level1 unnumbered" number="">
<h1>Appendix B - Scatter Plots</h1>
<div id="r-code-scatter-plots" class="section level3 unnumbered" number="">
<h3>R Code: Scatter Plots</h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>g1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(data) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">y =</span> Natsuki, <span class="dt">x =</span> Sayori) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-3"><a href="#cb15-3"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">col =</span> <span class="st">&#39;salmon&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-4"><a href="#cb15-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>) <span class="op">+</span></span>
<span id="cb15-5"><a href="#cb15-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;Fig. B - Trends in Points between </span></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="st">Characters&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-7"><a href="#cb15-7"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span>
<span id="cb15-8"><a href="#cb15-8"></a></span>
<span id="cb15-9"><a href="#cb15-9"></a>g2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(data) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-10"><a href="#cb15-10"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">y =</span> Natsuki, <span class="dt">x =</span> Yuri) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-11"><a href="#cb15-11"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">col =</span> <span class="st">&#39;cyan4&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-12"><a href="#cb15-12"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>) <span class="op">+</span></span>
<span id="cb15-13"><a href="#cb15-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&#39;</span><span class="ch">\n</span><span class="st">&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-14"><a href="#cb15-14"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span>
<span id="cb15-15"><a href="#cb15-15"></a></span>
<span id="cb15-16"><a href="#cb15-16"></a>g3 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(data) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-17"><a href="#cb15-17"></a><span class="st">  </span><span class="kw">aes</span>(<span class="dt">y =</span> Sayori, <span class="dt">x =</span> Yuri) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-18"><a href="#cb15-18"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">col =</span> <span class="st">&#39;forestgreen&#39;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb15-19"><a href="#cb15-19"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>) <span class="op">+</span></span>
<span id="cb15-20"><a href="#cb15-20"></a><span class="st">  </span><span class="kw">theme_light2</span>()</span>
<span id="cb15-21"><a href="#cb15-21"></a></span>
<span id="cb15-22"><a href="#cb15-22"></a><span class="kw">grid.arrange</span>(g1, g2, g3, <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">newpage =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="DDLC_web-alt_files/figure-html/appendixB-1.png" width="672" /></p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p><a href="https://ddlc.moe/" class="uri">https://ddlc.moe/</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Roe &amp; Mitchell (2019), p. 5.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Neri (2017), p. 7.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p><a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a><a href="#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>See Roe &amp; Mitchell (2019), p. 10.<a href="#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Corder &amp; Foreman (2009), p. 99-105.<a href="#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>Dunn (1964), p. 241-252.<a href="#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>See Corder &amp; Foreman (2009) and Dunn (1964).<a href="#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p><a href="https://doki-doki-literature-club.fandom.com/wiki/Act_1" class="uri">https://doki-doki-literature-club.fandom.com/wiki/Act_1</a><a href="#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p><a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a><a href="#fnref10" class="footnote-back">↩︎</a></p></li>
<li id="fn11"><p>Ogle (2019).<a href="#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p><a href="https://ddlcwiki.net/wiki/Poem_game" class="uri">https://ddlcwiki.net/wiki/Poem_game</a><a href="#fnref12" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
</div>



<script>
// when the page is about to reload via servr, remember the scroll position
document.addEventListener('servr:reload', function(e) {
  sessionStorage.setItem('pagedown-scroll', window.scrollY);
});
</script>
</body>
</html>
